### ISSUE TITLE
v2 refactor

### ISSUE THREAD

**Issue by Klooven** [Tutrox/scss-powertools#78]
- [x] required Node `>=10` #70 🛡
- [ ] testing for all steps in the process #1 🧫
- [ ] expose a public API #13 👋
- [x] write using `async/await`, `let + const`, and other strategies making the code more readable and efficient 🧱
- [ ] make docs more readable and correct typos #45 🗄
- [ ] clean cli 👩‍💻
- [ ] remove unnecessary packages 🧯
- [ ] use GitHub actions, make use of the tests 👨‍🏭
- [ ] (semi-)automate dependency updates and publishing when packages like autoprefixer receive new features 🐱‍👤

_More to come... maybe..._

Feedback is welcome! 👇

**Comment by Klooven** [comment]
Advanced configuration using cosmiconfig and the flag `-c`?

Usage cases:
- process multiple files
- custom stylelint preset
- custom postcss config

**Comment by Klooven** [comment]
☝ in this advanced configuration using a bunch of flags could be stripped, making it really easy to start using + more flexible to configure

**Comment by Klooven** [comment]
New `-s` (silent) mode could make the app less verbose, current mode would be checked in logger: https://github.com/Tutrox/scss-powertools/blob/f2f638250f838399fd8826c194c7cd5d08d53f4f/lib/logger.js#L12-L31

Could this be automatically enabled in production/CI-environments (`-p`)?

**Comment by Klooven** [comment]
v2 can be tested using `npm i scss-powertools@dev`

Not production ready though!

**Comment by erikverb** [comment]
![image](https://user-images.githubusercontent.com/7166388/79368180-a8da9100-7f57-11ea-9ce9-5a442971df81.png)
Incomplete error message, compilationn errors

**Comment by Klooven** [comment]
`node-sass` seems to be logging deprecation messages "without consent"?

Also it seems like the messages are multi-line 🤔

**Comment by Klooven** [comment]
Closing as `scss-powertools` is now in "maintenance mode"
